using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TankView : MonoBehaviour
{
    private TankController tankController;

    private float movement;
    private float rotation;

    public Rigidbody rb;

    public MeshRenderer[] childs;

    void Start()
    {
        GameObject cam =  GameObject.Find("Main Camera");
        cam.transform.SetParent(transform);
        cam.transform.position = new Vector3(0f, 3f, -4f);
    }

    void Update()
    {
        Movement();

        if (movement != 0)
            tankController.Move(movement, tankController.getTankModel().movementSpeed);

        if (rotation != 0)
            tankController.Rotate(rotation, tankController.getTankModel().rotationSpeed);
    }

    private void Movement()
    {
        movement = Input.GetAxis("Vertical");
        rotation = Input.GetAxis("Horizontal");
    }

    public void setTankController(TankController tank_controller)
    {
        tankController = tank_controller;
    }

    public Rigidbody getRigidbody()
    {
        return rb;
    }

    public void ChangeColor(Material tankColor)
    {
        for(int i = 0; i < childs.Length; i++) 
            childs[i].material = tankColor;
    }
}